# Programming Language Technology (Chalmers DAT151 / GU DIT231)
# (C) 2022-25 Andreas Abel
# All rights reserved.

# We use the recommended GHC version (9.6.7 as of 2025-11-02).
resolver: lts-22.44

# See https://www.stackage.org/ "Latest releases per GHC version"
# for alternatives.
